### PR TITLE
Add 'Spells & Shields' mod icons

### PR DESCRIPTION
**Pull request by CAS-ual-TY**
Hi,
you left a comment on [my mod, Spells & Shields](https://www.curseforge.com/minecraft/mc-mods/spells-shields). I checked out your profile and saw this. I have been using the resource pack equivalent for quite some time now and now found it as a mod which is awesome. Made this PR to support Spells & Shields. I hope this is all OK. I can also runData if needed. Will make more PRs in the future when I add more enchantments, if this is accepted.

### CODE REVIEW

**Comment by nekomaster1000** [comment]
Oh wow, fantastic! Next NEBs update, I’ll be sure to include these! Thanks for saving me the work, haha!

**Comment by CAS-ual-TY** [comment]
Great! Let me know when you publish it so I can add it to the list of integrations.

**Comment by CAS-ual-TY** [comment]
Oh and, sorry for double comment, may I try my hands on the magic protection icon? The current one seems a bit bland. Would love to do something more fancy.

**Comment by nekomaster1000** [comment]
I can't promise you I'll use your replacement, but I'd be happy for you to give it a go! The current one is supposed to represent the book seen on the Enchantment table, for context.

**Comment by CAS-ual-TY** [comment]
No asking for promises, just wanted to know if its even worth a try. Ill do something in a different PR

**Comment by nekomaster1000** [comment]
Small request: Could you refactor `mana_regen` to `mana_regeneration` please? Ars Nouveau already uses the `mana_regen` namespace, and I can only apply one sprite per namespace. I'd like both mods to have complete themed book sprites, and ask you over the Ars dev just because I have you in immediate contact.

**Comment by CAS-ual-TY** [comment]
Done. There might be other conflicts in the future with other integrations, so its probably a good idea to do this now.

**Comment by CAS-ual-TY** [comment]
The new version of Spells & Shields with the new enchantment id is published.

**Comment by nekomaster1000** [comment]
Awesome! It is out :] 👍 https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books/files/4018073

**Pull request closed without merging**
